### ISSUE TITLE
unable to run examples

### ISSUE THREAD

**Issue by gbr1** [arduino/arduino-modulino-mpy#1]
It seems impossible to run any example.
No I2C bus parameter is exposed in any example.

**Comment by sebromero** [comment]
The I2C bus is detected automatically for supported Arduino boards. For third party board the bus can be provided as follows:

```python
bus = I2C(0, freq=100000)
pixels = ModulinoPixels(bus)
pixels.set_all_rgb(0, 255, 0, 100)
pixels.show()
```

This is show in the`third_party_board.py` example. I just added a few more lines there to make it clearer.
