### ISSUE TITLE
knob.pressed() misses clicks

### ISSUE THREAD

**Issue by mo-seph** [arduino/arduino-modulino-mpy#4]
If a press happens between calls to update(), then it's not reported by knob.pressed(). This makes things very sensitive to the update frequency of the loop.

**Comment by sebromero** [comment]
Thank you @mo-seph for reporting this. The thing is, the knob modulino reports its current state in the moment. There is no buffering and there is no interrupt line available with QWIIC.
A solution is to use `asyncio`. This allows to run things "concurrently" which should minimize this issue. I added an example [here](../blob/main/examples/knob_async.py). Please let me know if that helps.

**Comment by sebromero** [comment]
Hi @mo-seph 👋 Did you get the chance to try out the new example?
